apiVersion: v1
kind: Pod
metadata:
  name: fastapi-pod
spec:
  containers:
    - name: api
      image: myfirstcontainer:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8000
      volumeMounts:
        - name: host-path-volume
          mountPath: /app  # Replace with the desired mount path in the container
  volumes:
    - name: host-path-volume
      hostPath:
        path: /mnt/c/Users/Alvaro_Vera/Desktop/RSSchool/modules/10.Containers/app  # Replace with the local path on your host machine