apiVersion: v1
kind: Pod
metadata:
  name: fastapi-pod
spec:
  containers:
    - name: api
      image: myfirstcontainer:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 8000
      env:
        - name: PORT
          value: "8000"